### ISSUE TITLE
Report use of @Column or @Element on a Collection

### ISSUE THREAD

**Issue by T1m07hy** [datanucleus/datanucleus-api-jdo#21] opened 2016-07-20 22:32 UTC
## Feature Request:

Add a check for situations where @Column or @Element is used on then Many side of a relation (Datatype List) causing only the first ID of Many relation is stored.

`   
@javax.jdo.annotations.PersistenceCapable
@javax.jdo.annotations.Inheritance(strategy = InheritanceStrategy.NEW_TABLE)
....
public abstract class Step {
    @Column(name = "toBeFinished", allowsNull = "true")
    private List<Step> stepsToBeFinished = Lists.newArrayList();`

Was generated with a column in the table but only the ID of the first element was stored. Instead I would have expected an error about this situation.

**Comment by andyjefferson** [comment] 2016-07-21 09:54
Specifying a @Column has nothing at all to do with what objects get persisted. It defines the SCHEMA and nothing more. If you want some extra checks for things kindly provide examples of WHAT, and WHAT happens (i.e reproduce some situation). You can use the testcase format to provide this.

**Comment by T1m07hy** [comment] 2016-07-25 12:24
Hi Andy,

I see - these attributes have their requirement, Please find attached a test case including a sample class demonstrating my issue.
It is about a class referencing itself, until now I found no other situation where my problem occurs.

Problem appears when you add two elements to field "toBeFinished".

Regards Timothy

Class demonstrating the issue:
`

@javax.jdo.annotations.PersistenceCapable(table = "SampleTest")
@javax.jdo.annotations.DatastoreIdentity(strategy = IdGeneratorStrategy.INCREMENT, column = "id")
@javax.jdo.annotations.Inheritance(strategy = InheritanceStrategy.NEW_TABLE)
@DomainObjectLayout(bookmarking = BookmarkPolicy.AS_CHILD, named = "SampleTest")
@DomainObject(editing = Editing.DISABLED)
public class SampleTest {

    final static Logger LOG = LoggerFactory.getLogger(SampleTest.class);

    /*
    this generates a field toBeFinished in Table SampleTest but as it is a 1:n relation
     */
    @Column(name = "toBeFinished", allowsNull = "true")
    private List<SampleTest> toBeFinished = Lists.newArrayList();

    @MemberOrder(sequence = "1")
    @CollectionLayout(named = "Waiting for to be finished", render = RenderType.EAGERLY)
    public List<SampleTest> getToBeFinished() {
        return toBeFinished;
    }

    public void setToBeFinished(final List<SampleTest> toBeFinished) {
        this.toBeFinished = toBeFinished;
    }

    /*
    this works perfect
     */
    @Persistent(table = "TO_BE_FINISHED")
    @Join(column = "SAMPLE_ID")
    @Element(column = "SAMPLE_TO_BE_FINISHED_ID")
    private List<Step> toBeFinishedWorking = Lists.newArrayList();

    @MemberOrder(sequence = "1")
    @CollectionLayout(named = "Waiting for steps to be finished", render = RenderType.EAGERLY)
    public List<Step> getToBeFinishedWorking() {
        return toBeFinishedWorking;
    }

    public void setToBeFinishedWorking(final List<Step> toBeFinishedWorking) {
        this.toBeFinishedWorking = toBeFinishedWorking;
    }
}

`

Test case that I added to our project for checking this:
`

public class InvalidCollectionMappingTest {

    private final static Logger LOG = LoggerFactory.getLogger(InvalidCollectionMappingTest.class);

    @Test
    public void testInvalidCollectionMapping() {

        final Map<Class, List<Field>> classList = new HashMap<>();

        //all persisted classes
        final Set<Class<?>> persistentClasses = new Reflections(FulfillmentAppDomainModule.class.getPackage().getName())
                .getTypesAnnotatedWith(PersistenceCapable.class);
        for (Class aClass : persistentClasses) {

            for (Field field : aClass.getDeclaredFields()) {
                if (Collection.class.isAssignableFrom(field.getType())) { //search for collections
                    ParameterizedType genericType = (ParameterizedType) field.getGenericType();
                    Class<?> relationClass = (Class<?>) genericType.getActualTypeArguments()[0];
                    if (relationClass.equals(aClass) && field.getAnnotation(Join.class)
                            == null) { //check if it references itself but has no @Join resulting in non working relation
                        LOG.error("Found field '" + field.getName() + "' of class '" + aClass
                                + "' being a collection without helper table.");
                        getObjectsFromTableMap(classList, aClass).add(field);
                    }
                }
            }
        }

        assertThat(classList).as("Found wrong relations").isEmpty();
    }

    private List<Field> getObjectsFromTableMap(Map<Class, List<Field>> map, Class aClass) {
        List<Field> fields = map.get(aClass);
        if (fields == null) {
            fields = new ArrayList<>();
            map.put(aClass, fields);
        }

        return fields;
    }
}

`

**Comment by andyjefferson** [comment] 2016-07-25 12:56
I don't see any "problem" demonstrated by the above "test". Specification of columns is only for SCHEMA specification and nothing else. Having a List field with persistable element with no annotations means you get a FK and order column in the table of the element, which is what you get.

If you add 2 elements to a self-referencing List it persists 2 elements. If you add THE SAME element to the List then it would clearly only persist 1 element (since the order column can only have 1 value). This is all as per the JDO spec. 

See a valid test at https://github.com/andyjefferson/api-jdo-21 , which is a simple Maven runnable project (using the Problem Reporting Guide). In this case I have a class Person (table PERSON). The FK is correctly generated (and the ordering column also) in the element classes table.

CREATE TABLE PERSON
(
    ID BIGINT NOT NULL,
    "NAME" VARCHAR(255) NULL,
    PEOPLE_ID_OWN BIGINT NULL,
    PEOPLE_INTEGER_IDX INTEGER NULL,
    CONSTRAINT PERSON_PK PRIMARY KEY (ID)
)

Nothing incorrect there.

**Comment by andyjefferson** [comment] 2016-07-28 10:13
Closing since it is not clear what you are wanting. If you take the GitHub test I included in the above comment and update it to demonstrate some particular situation then please attach it here and this can be re-opened.

**Closed by andyjefferson** 2016-07-28 10:13 UTC
Labels: testcase_required

**Comment by andyjefferson** [comment] 2019-05-02 14:11
My attempt to demonstrate this is now deleted since we are three years on from this "issue" that is not reproduceable
